<div class="piece atp123123123139">
<style>
/*common*/
body,p,ul,ol,dl,dt,dd,h1,h2,h3,h4,h5,h6,form,input,select,button,textarea,iframe,table,th,td,em{margin:0;padding:0;list-style: none;}
body,input,select,button,textarea{font-size:12px;font-family:arial,"微软雅黑",sans-serif;}
body{background: #e9e9e9;}
input{outline:none;}
a{text-decoration: none;}
a,a:focus{outline:none !important;}
img,a img{border: 0;vertical-align: top;}
.shopicon{display: inline-block;background-image: url($GRUNTCONFIG.DEV.thinkpcimagespath/shopicon.png);background-repeat: no-repeat;}
.clearfix:after{display: block;clear: both;height: 0;visibility: hidden;font-size: 0;line-height: 0;content: "";}
.clearfix{zoom:1;}
/*shop_nav*/
.shop_nav{float: left;width: 207px;}
.shop_nav_con{width: 207px;}
.shop_nav_con h1{height: 48px;line-height: 48px;background: #e72e25;color: #fff;font-size: 14px;font-weight: normal;padding-left: 20px;}
.shop_nav_category{background: #000;height: 300px;position: relative;z-index: 10;}
.shop_nav_link{display: block; height: 50px;line-height: 50px;font-size: 15px;color: #fff;padding-left: 20px;}
.shop_nav_link:hover,.shop_nav_link.active{background: #fff;}
.shop_nav_link .shop_nav_txt,.shop_nav_link.active .shop_nav_txt{color: #fff;margin-left: 15px;}
.shop_nav_link:hover .shop_nav_txt,.shop_nav_link.active .shop_nav_txt{color: #e72e25;}
.shop_nav_link .shopicon{width: 20px;height: 20px;float: left;margin-top: 14px;}
.shop_nav_link .shop_nav_pc{background-position: -5px -2px;}
.shop_nav_link:hover .shop_nav_pc,.shop_nav_link.active .shop_nav_pc{background-position: -33px -2px;}
.shop_nav_link .shop_nav_desktop{background-position: -4px -30px;}
.shop_nav_link:hover .shop_nav_desktop,.shop_nav_link.active .shop_nav_desktop{background-position: -32px -30px;}
.shop_nav_link .shop_nav_display{background-position: -5px -57px;}
.shop_nav_link:hover .shop_nav_display,.shop_nav_link.active .shop_nav_display{background-position: -33px -57px;}
.shop_nav_link .shop_nav_option{background-position: -5px -84px;}
.shop_nav_link:hover .shop_nav_option,.shop_nav_link.active .shop_nav_option{background-position: -33px -84px;}
.shop_nav_link .shop_nav_service{background-position: -5px -111px;}
.shop_nav_link:hover .shop_nav_service,.shop_nav_link.active .shop_nav_service{background-position: -33px -111px;}
.shop_nav_link .shop_nav_life{background-position: -5px -139px;}
.shop_nav_link:hover .shop_nav_life,.shop_nav_link.active .shop_nav_life{background-position: -33px -139px;}

.shop_nav_child{position: absolute;left: 207px;top: 0px;background: #fff;width: 150px;z-index: 10;display: none;}
.shop_nav_child .nav_child_link{display: block;height: 37px;line-height: 37px;padding: 0 20px;}
.shop_nav_child .nav_child_link:hover,.shop_nav_child .nav_child_link.active{background: #f8f8f8;color: #e72e25;}
.shop_nav_child .nav_child_link em{width: 5px;height: 9px;background-position: -38px -179px;float: right;margin-top: 13px;}
.shop_nav_child .nav_child_link:hover em,.shop_nav_child .nav_child_link.active em{background-position: -48px -179px;}
.shop_nav_child .nav_child_link span{float: left;}

.shop_nav_children{position: absolute;top: 0;left: 150px;width: 170px;background: #f8f8f8;z-index: 10;display: none;}
.shop_nav_children .nav_children_link{display: block;height: 37px;line-height: 37px;padding-left: 15px;}
</style>
<div class="shop_nav_con">
<h1>全部商品分类</h1>
    <ul class="shop_nav_category">
        <li class="shop_nav_item">
            <a href="http://s.thinkworldshop.com.cn/?index=0" target="_blank" class="shop_nav_link">
                <span class="shopicon shop_nav_pc"></span>
                <span class="shop_nav_txt">笔记本</span>
            </a>
        </li>
        <li class="shop_nav_item">
            <a href="http://s.thinkworldshop.com.cn/?index=1" target="_blank" class="shop_nav_link">
                <span class="shopicon shop_nav_desktop"></span>
                <span class="shop_nav_txt">台式机</span>
            </a>
        </li>
        <li class="shop_nav_item">
            <a href="http://s.thinkworldshop.com.cn/?index=2" target="_blank" class="shop_nav_link">
                <span class="shopicon shop_nav_display"></span>
                <span class="shop_nav_txt">平板</span>
            </a>
        </li>
        <li class="shop_nav_item">
            <a href="http://s.thinkworldshop.com/?index=3" target="_blank" class="shop_nav_link">
                <span class="shopicon shop_nav_option"></span>
                <span class="shop_nav_txt">电脑周边</span>
            </a>
        </li>
        <li class="shop_nav_item">
            <a href="http://s.thinkworldshop.com.cn/?index=4" target="_blank" class="shop_nav_link">
                <span class="shopicon shop_nav_service"></span>
                <span class="shop_nav_txt">ThinkLife</span>
            </a>
        </li>
        <li class="shop_nav_item">
            
        </li>
    </ul>
</div>
</div>