<div class="piece a126123123129">
	<div id="think_header">
		<div class="think_head_con clearfix">
			<div class="think_logo">
				<a href="http://www.thinkworldshop.com.cn" title=""><img
					src="http://m1.lefile.cn/tp/images/think_logo.png" alt="" />
				</a>
				<a href="http://www.thinkworldshop.com.cn" title=""><img
				    src="http://m1.lefile.cn/tp/images/think_logogif.gif" alt="" />
			    </a>		
			</div>
			<div class="think_nav">
				<ul class="think_navul clearfix">
					<li class="think_li navpad"><a href="http://www.thinkworldshop.com.cn/home_index.html"
						title="首页" class="th_nava">首页</a>
					</li>
					<li class="think_li navpad"><a href="http://www.thinkworldshop.com.cn/thinkshop_index.html"
						title="官方商城" class="th_nava">官方商城</a>
					</li>
					<li class="think_li navpad"><a
						href="http://bbs.thinkworldshop.com.cn/" title="社区"
						class="th_nava">社区</a>
					</li>
					<li class="think_li" style="padding-right:0;"><a
						href="http://think.lenovo.com.cn/" title="服务与支持" class="th_nava">服务与支持</a>
					</li>
				</ul>
				<div class="think_nav_border"></div>
			</div>
			<div class="think_car">
				<a href="http://cart.thinkworldshop.com.cn" title="购物车" class="usepng">购物车<i></i>
				</a>
			</div>
			<div class="think_user">
				<div class="think_login clearfix">
					<a href="javascript:logobj.showregist();" title="注册">注册</a><span>|</span><a
						href="javascript:logobj.showlogin();" title="登录">登录</a>
				</div>
				<div class="think_register clearfix" style="display:none;">
					<a href="javascript:logobj.dologout();" title="退出">退出</a><span>|</span><a
						href="http://www.thinkworldshop.com.cn/user/index.html" title="用户名" class="ellipsis">花开的季节-13552280356</a>
				</div>
			</div>
			<div class="think_search">
				<input type="text" placeholder="ThinkPad X1" latag="latag_pc_search_keyword" />
                <button class="usepng" type="button" latag="latag_pc_search_confirm">搜索</button>
                <div id="suggestContainer"></div>
			</div>
		</div>
	</div>
</div>


