<div class="piece atp123123123172">
	<div id="think_footer">
	    <div class="think_share clear">
	        <a class="th_douban" title="豆瓣" href="http://site.douban.com/thinkpad/" target="_blank">豆瓣</a>
	        <a class="th_weibo" title="微博" href="http://weibo.com/lenovothink" target="_blank">微博</a>
	        <a class="th_renren" title="人人" href="http://page.renren.com/600014223?checked=true" target="_blank">人人</a>
	        <a class="th_tencent" title="腾讯微博" href="http://e.t.qq.com/ilovethinkpad" target="_blank">腾讯微博</a>
	    </div>
	    <div class="think_link">
	        <ul class="clear">
	            <li style="padding-left:0;"><a style="color:red;" href="http://www.thinkworldshop.com.cn/static/legal_notice.html" target="_blank" title="法律公告">法律公告</a></li>
	            <li><a href="http://www.thinkworldshop.com.cn/login/about_member.html" target="_blank" title="关于会员">关于会员</a></li>
	            <li><a href="http://think.lenovo.com.cn/" target="_blank" title="服务与支持">服务与支持</a></li>
	            <li><a style="color:red;" href="javascript:iframeBox('意见反馈','750','300','http://www.thinkworldshop.com.cn/user/feedback.html');" target="_blank" title="官网意见反馈">官网意见反馈</a></li>
	            <li><a href="http://www.thinkworldshop.com.cn/static/privacy_protection.html" target="_blank" title="隐私保护">隐私保护</a></li>
	            <li><a href="http://www.lenovo.com.cn" target="_blank" title="联想官方站">联想官方站</a></li>
	            <li><a href="http://www.zuk.com/?hmsr=thinkpad&hmmd=logo" target="_blank" title="神奇工厂">神奇工厂</a></li>
	            <li><a href="http://products.thinkworld.com.cn/thinkproducts/product/getPartners" target="_blank" title="合作伙伴认证">合作伙伴认证</a></li>
	            <li><a href="http://www.thinkworldshop.com.cn/contact/index.html" target="_blank" title="联系我们">联系我们</a></li>
	            <li><a href="http://www.thinkworldshop.com.cn/product/index.html" target="_blank" title="产品查询">产品查询</a></li>
	            <li><a href="http://fs.thinkworldshop.com.cn" target="_blank" title="fans专属">fans专属</a></li>
	            <li style="border-right:0;"><a href="http://b2b.thinkworldshop.com.cn" target="_blank" title="经销商注册">经销商注册</a></li>
	        </ul>
	    </div>
	    <div class="think_copy">
		<p>ThinkWorld和ThinkWorldShop为联想ThinkPad官方网站，网站指定运营商为北京佳意堂广告有限公司。</p>
	        <p>版权所有：北京佳意堂广告有限公司 京ICP备14036778</p>
	        <p>超极本,赛扬、Celeron Inside、CoreInside、英特尔、英特尔标识、英特尔凌动、Intel Atom Inside、英特尔酷睿、Intel Inside, Intel Inside 标识、英特尔欢跃、英特尔博锐、安腾、Itanium Inside、奔腾、Pentium Inside、vPro Inside、至强、至强 Phi 和 Xeon Inside 均是英特尔公司在美国或其他国家的商标。ThinkPad是联想公司的注册商标。</p>
	    </div>
	</div>
</div>
