<div class="piece atp123123123171">
	<div id="T_service">
		<div class="t_service_con clearfix">
			<div id="shop_contact">
				<a
					href="http://www.thinkworldshop.com.cn/activity/Carbon/index.html"
					target="_blank" name="footer_t10"> <img
					src="http://m1.lefile.cn/tp/images/footer_number.png"> </a>
			</div>
			<ul>
				<li><i class="i01"></i>
					<h2>购物指南</h2> <a href="http://www.thinkworldshop.com.cn/static/shop.html" target="_blank">购物指南</a><a
					href="http://www.thinkworldshop.com.cn/static/shop.html" target="_blank">会员注册</a>
				</li>
				<li><i class="i02"></i>
					<h2>配送方式</h2> <a href="http://www.thinkworldshop.com.cn/static/logistics.html#logistics_q"
					target="_blank">签收原则</a> <a
					href="http://www.thinkworldshop.com.cn/static/logistics.html#logistics_p" target="_blank">配送方式</a>
					<a href="http://www.thinkworldshop.com.cn/static/logistics.html#logistics_s" target="_blank">配送物流</a>
				</li>
				<li><i class="i03"></i>
					<h2>支付及订单</h2> <a href="http://www.thinkworldshop.com.cn/static/payment.html#payment_z"
					target="_blank">支付宝支付</a> <a href="http://www.thinkworldshop.com.cn/static/payment.html#payment_h"
					target="_blank">货到付款</a> <a href="http://www.thinkworldshop.com.cn/static/payment.html#payment_f"
					target="_blank">发票制度</a>
					<a href="http://www.thinkworldshop.com.cn/static/pay_help.html" target="_blank">支付帮助</a>
				</li>
				<li><i class="i04"></i>
					<h2>售后服务</h2> <a href="http://www.thinkworldshop.com.cn/static/after_index.html" target="_blank">笔记本售后服务</a>
					<a href="http://www.thinkworldshop.com.cn/static/accessories.html" target="_blank">官方选件售后服务</a>
				</li>
				<li style="width:90px;"><i class="i05"></i>
					<h2>其他信息</h2> <a style="color:red;"
					href="http://products.thinkworld.com.cn/thinkproducts/product/tothinkstore"
					class="bhot" target="_blank">线下体验店</a> 
					<a href="http://www.thinkworldshop.com.cn/static/black_red.html" target="_blank">黒点说明</a>
					<a href="http://www.thinkworldshop.com.cn/static/goods_sm.html" target="_blank">产品和性能声明</a>
					
				</li>
			</ul>
		</div>
	</div>
</div>